site_name: The FRC Programming Guide
theme:
  name: material
  palette:
    scheme: slate
    accent: yellow

watch:
  - docs
  - docs/Basic-FRC-Programming
  - docs/Advanced-FRC-Programming

nav:
  - Welcome to the Frc Programming Guide: 'index.md'
  - Basic Frc Programming:
    - 'Basic-FRC-Programming/1.md'
    - 'Basic-FRC-Programming/2.md'
    - 'Basic-FRC-Programming/3.md'
    - 'Basic-FRC-Programming/4.md'
    - 'Basic-FRC-Programming/5.md'
    - 'Basic-FRC-Programming/6.md'
    - 'Basic-FRC-Programming/7.md'
    - 'Basic-FRC-Programming/8.md'
  - Advanced Frc Programming:
    - 'Advanced-FRC-Programming/1.md'
    - 'Advanced-FRC-Programming/2.md'
    - 'Advanced-FRC-Programming/3.md'
    - 'Advanced-FRC-Programming/4.md'
    - 'Advanced-FRC-Programming/5.md'
    - 'Advanced-FRC-Programming/6.md'
    - 'Advanced-FRC-Programming/7.md'
  - How To Troubleshoot: 'troubleshooting.md'
  - Notes: 'notes.md'

extra_javascript:
  - https://cdn.jsdelivr.net/npm/chart.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - tables
  - mdx_math:
      enable_dollar_delimiter: True